vich_uploader:
    db_driver: orm

    mappings:
        super_heros:
            uri_prefix: \images\super_heros
            upload_destination: '%kernel.project_dir%\public\images\super_heros'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
